
services:
  - type: web
    name: discord-love-bot
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/server/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HUSBAND_ID
        sync: false
      - key: WIFE_ID
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
