
services:
  - type: web
    name: discord-love-bot
    env: node
    buildCommand: npm ci && npm run build
    startCommand: NODE_ENV=production node dist/server/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HUSBAND_ID
        sync: false
      - key: WIFE_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: discord-love-bot-db
          property: connectionString
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: discord-love-bot-db
    plan: free
    postgresMajorVersion: 15
